AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mercator Text Extraction Pipeline Stack'
Parameters:
  DefaultBucket:
    Type: String
    Default: mercator-test
    Description: default S3 bucket for the project
  FormsBucket:
    Type: String
    Default: mercator-test
    Description: S3 bucket hosting the application forms
  ScriptsBucket:
    Type: String
    Default: mercator-test
    Description: S3 bucket hosting lambda zip file
  QueriesAnswersS3Bucket:
    Type: String
    Default: mercator-test
    Description: AWS Region for Amazon Textract
  FormsS3Prefix:
    Type: String
    Default: pdfs
    Description: S3 prefix (folder) where application forms are stored
  LambdaValidateFormZipFileKey:
    Type: String
    Default: lambda_validate_form.zip
    Description: S3 key where validation lambda function zip file is stored
  LambdaExecuteQueriesZipFileKey:
    Type: String
    Default: lambda_execute_queries.zip
    Description: S3 key where query-execution lambda function zip file is stored
  LambdaHandleValidationFailureZipFileKey:
    Type: String
    Default: lambda_handle_validation_failure.zip
    Description: S3 key where the zip file of the lambda function for handling validation failure is stored  
  LambdaPackageZipFileKey:
    Type: String
    Default: lambda_package.zip
    Description: S3 key where lambda package zip file is stored
  StateMachineJSONKey:
    Type: String
    Default: state_machine.json
    Description: S3 key where state machine definition file is stored
  QueriesS3Key:
    Type: String
    Default: queries.json
    Description: S3 key where the queries json file is stored
  ValidationAnswersS3Key:
    Type: String
    Default: validation-answers.json
    Description: S3 key where validation answer json file is stored
  ValidationQueriesS3Key:
    Type: String
    Default: validation-queries.json
    Description: S3 key where validation queries json file is stored
  LambdaRoleArn:
    Type: String
    Default: arn:aws:iam::706676680875:role/Lambda_Exec
    Description: Lambda Role ARN
  EventBridgeInvokeStepFunctionRoleArn:
    Type: String
    Default: arn:aws:iam::706676680875:role/service-role/Amazon_EventBridge_Invoke_Step_Functions_1997196675
    Description: ARN for EventBridge Role to invoke step functions
  TextractRegionName:
    Type: String
    Default: us-east-1
    Description: AWS Region for Amazon Textract
Resources:
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TextractStateMachineInvokeLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Path: /
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TextractLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonTextractFullAccess
      Path: /
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TextractEventBridgeInvokeStateMachineRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
      Path: /  
  LambdaValidateForm:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LambdaValidateForm
      Description: Lambda function for validating uploaded application
      Runtime: python3.9
      Handler: lambda_validate_form.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 300
      Code:
        S3Bucket: !Ref ScriptsBucket
        S3Key: !Ref LambdaValidateFormZipFileKey
      Layers: 
        - !Ref Libs
      Environment:
        Variables:
          TextractRegionName: !Ref TextractRegionName
          QueriesAnswersS3Bucket: !Ref QueriesAnswersS3Bucket
          QueriesS3Key: !Ref QueriesS3Key
          ValidationAnswersS3Key: !Ref ValidationAnswersS3Key
          ValidationQueriesS3Key: !Ref ValidationQueriesS3Key         
          FormsBucket: !Ref FormsBucket    
  LambdaExecuteQueries:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LambdaExecuteQueries
      Description: Lambda function for parsing application forms using Textract
      Runtime: python3.9
      Handler: lambda_execute_queries.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 300
      Code:
        S3Bucket: !Ref ScriptsBucket
        S3Key: !Ref LambdaExecuteQueriesZipFileKey
      Layers: 
        - !Ref Libs
      Environment:
        Variables:
          TextractRegionName: !Ref TextractRegionName
          QueriesAnswersS3Bucket: !Ref QueriesAnswersS3Bucket
          QueriesS3Key: !Ref QueriesS3Key      
          FormsBucket: !Ref FormsBucket   
  LambdaHandleValidationFailure:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LambdaHandleValidationFailure
      Description: Lambda function for handling validation failure
      Runtime: python3.9
      Handler: lambda_handle_validation_failure.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 300
      Code:
        S3Bucket: !Ref ScriptsBucket
        S3Key: !Ref LambdaHandleValidationFailureZipFileKey
      Layers: 
        - !Ref Libs 
  Libs:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: mercator-textract
      Description: Dependencies for the textract pipeline.
      Content:
        S3Bucket: !Ref ScriptsBucket
        S3Key: !Ref LambdaPackageZipFileKey
  TextractStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: textractStateMachine
      DefinitionS3Location:
        Bucket: !Ref ScriptsBucket
        Key: !Ref StateMachineJSONKey
      DefinitionSubstitutions:
        LambdaValidateForm: !GetAtt LambdaValidateForm.Arn
        LambdaExecuteQueries: !GetAtt LambdaExecuteQueries.Arn
        LambdaHandleValidationFailure: !GetAtt LambdaHandleValidationFailure.Arn
      RoleArn: !GetAtt StateMachineRole.Arn
  S3TextractEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: S3 trigger for Textract state machine
      Name: S3TriggerTextractStateMachine
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref FormsBucket
          object:
            key:
              - prefix: !Ref FormsS3Prefix
      State: ENABLED
      Targets:
        - Arn: !GetAtt TextractStateMachine.Arn
          Id: TextractStateMachineId
          RoleArn: !Ref EventBridgeInvokeStepFunctionRoleArn
          RetryPolicy:
            MaximumRetryAttempts: 3
            MaximumEventAgeInSeconds: 60
